### ISSUE TITLE
Rename to have `action` in name?

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/reverse-dependency-testing-action#1]
I would think it would be nice if all github actions in this org would follow the same naming pattern. I would love it to be `action-x-y-z`, or `actions-x-y-z`, but while browsing through the repos it seems that most already follow the naming scheme of x-y-z-action. 

So with that in mind, I would propose to rename this one `reverse-dependency-testing-action`.

What do you think @martinfleis? We don't yet have a policy, and may not even want to have one, it would be just nice on the long term to have the most self-descriptive names (not just actions, but for bots, plugins, etc.)

**Comment by martinfleis** [comment]
I have originally excluded `action` from the repo name as the actions we usually use do not contain it either. But I don't have a strong opinion on this, so if we want to rename to be consistent, let's go for it.

**Comment by crazy4pi314** [comment]
I think there is some value in being consistent adding the action/pytest/plugin sort of qualifier as then someone who is browsing through projects can quickly understand what kind of thing is doing reverse dependency testing. YYMV

**Comment by martinfleis** [comment]
I don't have rights to rename the repository. @bsipocz can you do that?

**Comment by bsipocz** [comment]
@martinfleis - What would be the name you prefer?

**Comment by martinfleis** [comment]
@bsipocz I'd go with your proposal `reverse-dependency-testing-action` to be in line with `upload-nightly-action`.

**Comment by bsipocz** [comment]
Done!
